services:
  - type: web
    name: PARKY-WEB
    env: node
    buildCommand: yarn install
    startCommand: node index.js
    plan: free
    region: oregon # ou votre région préférée
    branches:
      - main # ou votre branche de déploiement
